version: '3'
services:
  postgres:
    build:
      context: ./
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: topics
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1273

  spring-app:
    build:
      context: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgres
